const BAD_REQUEST = 400
const SUCCESS = 200
const CREATED = 201
const NOT_FOUND = 404
const SERVER_ERROR = 500
const NOT_AUTHENTIACTED = 401

module.exports = {BAD_REQUEST, SUCCESS, CREATED, NOT_FOUND, SERVER_ERROR, NOT_AUTHENTIACTED}